# replace .war with .jar or .ear if needed
name: Whitesource Prioritize Java with Maven
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: WhiteSource Unified Agent Scan
      run: |
        chmod +x ./workshop-setup-Github.sh && ./workshop-setup-Github.sh
