name: TS workshop setup
on: workflow_dispatch

env:
 GH_USERS_PER_ORG: 1
    
jobs:
  Workshop-setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Workshop-setup-github
      env:
        GH_TOKEN: ${{secrets.GH_TOKEN}}
        GH_ORGS: "mendts-workshop, mendts-workshop1, mendts-workshop2"
        GH_USERNAME: ts-whitesource
        GH_BRANCH: easybuggy
      run: |
        chmod +x ./workshop-setup-github.sh
        ./workshop-setup-github.sh ghusers.txt
    - name: Workshop-setup-sca
      env:
        WS_APIKEYS: ${{secrets.WS_APIKEYS}}
        WS_USERKEYS: ${{secrets.WS_USERKEYS}}
        WS_WSS_URL: https://saas.mend.io/api/v1.3
        WS_INVITERS: "tsworkshop@whitesourcesoftware.com, tsworkshop1@whitesourcesoftware.com, tsworkshop2@whitesourcesoftware.com"
      run: |
        chmod +x ./workshop-setup-sca.sh
        ./workshop-setup-sca.sh emails.txt
        
