# replace .war with .jar or .ear if needed
name: Whitesource Prioritize Java with Maven
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Script
      run: chmod +x ./workshop-setup-github.sh
      shell: bash
    - name: Script2
      run: ./workshop-setup-github.sh ghusers.txt
      shell: bash
