# replace .war with .jar or .ear if needed
name: Whitesource Prioritize Java with Maven
on: workflow_dispatch

env:
  BUILD_TYPE: Release
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Script4
      run: |
        sed 's/^M$//' workshop-setup-github.sh>workshop-setup-github.sh
        chmod +x ./workshop-setup-github.sh && ./workshop-setup-github.sh ghusers.txt
