name: TS workshop setup
on: workflow_dispatch

#env:
#  BUILD_TYPE: Release
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Workshop-setup
#      shell: pwsh
#      env:
#        GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
      run: |
        chmod +x ./workshop-setup-github.sh
        ./workshop-setup-github.sh ghusers.txt
