# 
name: Mend workshop setup
on: workflow_dispatch
jobs:
  Workshop-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Run build script
        run: .github/workshop-setup-Github.sh
        shell: bash
